[package]
name = "astrustpy"
version = "0.1.0"
authors = ["Tom & Erik"]
edition = "2018"

[dependencies]
kuchiki = "0.8.0"
pyo3 = { version = "0.19.2", features = ["extension-module"] }
tendril = "0.4.3"

[lib]
name = "stats"
crate-type = ["cdylib"]
path = "rust/lib.rs"
